name: Docker Image CI

on: 
   push: 
      branches: [master, beta, develop] 
   
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install 
        

    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: run build 

    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: run build:preview 

    
    - name: set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
         images: flora300923/ant-design-vue-pro
   
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io


    - name: Build and push
      run: |
        docker build . --file Dockerfile --tag docker.io/${{ steps.meta.outputs.tags }}:$GITHUB_SHA
        docker push docker.io/${{ steps.meta.outputs.tags }}:$GITHUB_SHA

   
 
