name: Docker Image CI

on: [push]
   

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install 
        

    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: run build 

    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: run build:preview 
        
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    
    - name: Set Docker tag
      id: tag
      uses: ant-design-vue-pro/docker-tag-action@v4
    
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build -t ant-design-vue-pro:${{ steps.tag.outputs.docker-tag }} .
        docker push ant-design-vue-pro:${{ steps.tag.outputs.docker-tag }}
