name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install 
        
    - name: Run serve
      uses: borales/actions-yarn@v4
      with:
        cmd: run serve 

    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: run build 

    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: run build:preview 
    
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
