name: Docker Image CI

on: [push]
   

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install 
        

    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: run build 

    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: run build:preview 
        
    - name: what
      run: echo floraa-w/ant-design-vue-pro:${GITHUB_REF##*/}

    
    - name: set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
   
    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io


    - name: Build and push
      uses: docker/build-push-action@v2
      with:
         context: ./docker
         file: ./docker/Dockerfile
         platforms: linux/amd64,linux/arm64,linux/386
         push: true
         tags: floraa-w/ant-design-vue-pro:${GITHUB_REF##*/}
         build-args: |
            BRANCH=${GITHUB_REF##*/}
